build(global): update everything and enfore commits

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,26 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+
 npx lint-staged
+
+
+currentBranch=$(git branch --show-current)
+
+#if we are on master, main or develop, we run the test and enforce coverage
+
+if [ "$currentBranch" = "master" ] || [ "$currentBranch" = "main" ] || [ "$currentBranch" = "develop" ]; then
+  echo "Running tests and enforcing coverage"
+  npm run build --noEmit --silent
+  
+  npm run test --silent --bail --coverage --coverageReporters='json-summary' 2> /dev/null
+  
+  # Get the coverage percentage and fail if its less than 90%
+  pct=$(cat coverage/coverage-summary.json | jq '.total."lines"."pct"')
+  if [ $pct -lt 90 ]; then
+    echo "Commit Denied: Coverage is less than 90%: $pct"
+    exit 1
+  fi
+fi
+
+
